name: Keep Streamlit App Awake

on:
  schedule:
    # Cứ mỗi 30 phút, robot GitHub sẽ vào "đánh thức" app một lần
    - cron: '*/30 * * * *'
  workflow_dispatch: # Cho phép bấm chạy thủ công nếu muốn

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a request to Streamlit App
        run: |
          curl -I https://saigonmed-kho.streamlit.app/
